use_frameworks!

platform :ios, '8.0'

target 'WQAudioWaveFormView_Example' do
  pod 'WQAudioWaveFormView', :path => '../'

  target 'WQAudioWaveFormView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
